
import type { Metadata } from 'next'
import '@/app/ui/global.scss';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): React.ReactNode {
  return (
    <html lang="en">
      <body className='bodyGlobal'>{children}</body>
    </html>
  );
}